name: manusanchev-CI-CD

on:
  push:
    branches: [ master ]

jobs:
  build_and_push:
    name: Build and push image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Build container image
        run: docker build -t manusanchev/portfolio:$(echo $GITHUB_SHA | head -c7) .

      - name: Login to Docker Hub
        run:  docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push container image to docker hub
        run: docker push manusanchev/portfolio:$(echo $GITHUB_SHA | head -c7)

  deploy:
      name: Deploy to digital ocean
      runs-on: ubuntu-latest
      needs: build_and_push
      steps:
        - name: execute ssh
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.HOST }}
            username: ${{ secrets.USERNAME }}
            key: ${{ secrets.KEY }}
            passphrase: ${{ secrets.PASSPHRASE }}
            port: ${{ secrets.PORT }}
            script: |
              # pull from registry
              docker pull manusanchev/portfolio:$(echo $GITHUB_SHA | head -c7)
              # Stop running container
              docker stop portfolio
              # Remove old container
              docker rm portfolio
              # Run a new container from a new image
              docker run -dp 3000:3000 \
              --restart always \
              --name portfolio \
              manusanchev/portfolio:$(echo $GITHUB_SHA | head -c7)