name: manusanchev-CI-CD

on:
  push:
    branches: [ master ]

env:
  IMAGE_REPO: "manusanchev/portfolio"

jobs:
  build_and_push:
    name: Build and push image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Build container image
        run: docker build -t $(echo $IMAGE_REPO):$(echo $GITHUB_SHA | head -c7) .

      - name: Login to Docker Hub
        run:  echo "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}" | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin

      - name: Push container image to docker hub
        run: docker push $(echo $IMAGE_REPO):$(echo $GITHUB_SHA | head -c7)

  deploy:
      name: Deploy to digital ocean
      runs-on: ubuntu-latest
      needs: build_and_push
      env:
        DOCKER_PROCESS_NAME: "portfolio"
      steps:
        - name: execute ssh
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.HOST }}
            username: ${{ secrets.USERNAME }}
            key: ${{ secrets.KEY }}
            passphrase: ${{ secrets.PASSPHRASE }}
            port: ${{ secrets.PORT }}
            envs: IMAGE_REPO, GITHUB_SHA, DOCKER_PROCESS_NAME
            script: |
              # pull from registry
              docker pull $(echo $IMAGE_REPO):$(echo $GITHUB_SHA | head -c7)
              # Stop running $(echo $DOCKER_PROCESS_NAME)
              docker stop $(echo $DOCKER_PROCESS_NAME)
              # Remove old container
              docker rm $(echo $DOCKER_PROCESS_NAME)
              # Run a new container from a new image
              docker run -dp 3000:3000  --restart always --name $(echo $DOCKER_PROCESS_NAME) $IMAGE_REPO:$(echo $GITHUB_SHA | head -c7)